<?php

namespace Database\Seeders;

use App\Models\Room;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RoomSeeder extends Seeder
{
  public function run(): void
  {
    Room::insert([
      [
        "id" => 1002,
        "location_id" => 1,
        "floor" => "1.OG",
        "name" => "1.02",
        "alt_name" => "Computer- und Schulungsraum ",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1004,
        "location_id" => 1,
        "floor" => "1.OG",
        "name" => "1.07",
        "alt_name" => "Schulungsraum neben Sportraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1007,
        "location_id" => 1,
        "floor" => "1.OG",
        "name" => "1.10",
        "alt_name" => "Schulungsraum neben Sitzecke ",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1008,
        "location_id" => 1,
        "floor" => "1.OG",
        "name" => "1.11",
        "alt_name" => "Schulungsraum Fenster ",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1013,
        "location_id" => 1,
        "floor" => "3.OG",
        "name" => "3.09",
        "alt_name" => "Rückkehrer. Schulungsraum ",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1201,
        "location_id" => 2,
        "floor" => "EG",
        "name" => "0.01",
        "alt_name" => "Schulungsraum CAD_ECOM",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1203,
        "location_id" => 2,
        "floor" => "EG",
        "name" => "0.03",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1204,
        "location_id" => 2,
        "floor" => "1.OG",
        "name" => "1.01",
        "alt_name" => "Prüfungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1206,
        "location_id" => 2,
        "floor" => "2.OG",
        "name" => "2.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1208,
        "location_id" => 2,
        "floor" => "3.OG",
        "name" => "3.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1210,
        "location_id" => 2,
        "floor" => "4.OG",
        "name" => "4.03",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1301,
        "location_id" => 3,
        "floor" => "EG",
        "name" => "0.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1401,
        "location_id" => 4,
        "floor" => "EG",
        "name" => "0.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1403,
        "location_id" => 4,
        "floor" => "EG",
        "name" => "0.03",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1404,
        "location_id" => 4,
        "floor" => "EG",
        "name" => "0.04",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1405,
        "location_id" => 4,
        "floor" => "DG",
        "name" => "4.01",
        "alt_name" => "Videoteam",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1406,
        "location_id" => 4,
        "floor" => "EG/5",
        "name" => "0.01 /5",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1407,
        "location_id" => 4,
        "floor" => "EG/6",
        "name" => "0.02 /5",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1501,
        "location_id" => 5,
        "floor" => "1.OG",
        "name" => "1.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1502,
        "location_id" => 5,
        "floor" => "2.OG",
        "name" => "2.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1505,
        "location_id" => 5,
        "floor" => "3.OG",
        "name" => "3.02",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1601,
        "location_id" => 6,
        "floor" => "1.OG",
        "name" => "1.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1603,
        "location_id" => 6,
        "floor" => "1.OG",
        "name" => "1.04",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1606,
        "location_id" => 6,
        "floor" => "2.OG",
        "name" => "2.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1608,
        "location_id" => 6,
        "floor" => "2.OG",
        "name" => "2.03",
        "alt_name" => "Schulungsraum Hintern",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 1701,
        "location_id" => 7,
        "floor" => "EG",
        "name" => "0.01",
        "alt_name" => "Schulungsraum/Prüfungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 2101,
        "location_id" => 8,
        "floor" => "EG",
        "name" => "0.01",
        "alt_name" => "IBO/OSI- Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 2102,
        "location_id" => 8,
        "floor" => "EG",
        "name" => "0.02",
        "alt_name" => "ISO-Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 2002,
        "location_id" => 9,
        "floor" => "EG",
        "name" => "0.02",
        "alt_name" => "Schulungsraum (E-Com-Raum)",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 2003,
        "location_id" => 9,
        "floor" => "EG",
        "name" => "0.08",
        "alt_name" => "Schulungsraum (gegnüb.Küche",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 2004,
        "location_id" => 9,
        "floor" => "EG",
        "name" => "0.09",
        "alt_name" => "Schulungsraum (Blücher unten)",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 2010,
        "location_id" => 9,
        "floor" => "1.OG",
        "name" => "1.09",
        "alt_name" => "Schulungsraum (OG ganz hinten)",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 2011,
        "location_id" => 9,
        "floor" => "1.OG",
        "name" => "1.10",
        "alt_name" => "Schulungsraum (ggü. Schneider)",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 2012,
        "location_id" => 9,
        "floor" => "1.OG",
        "name" => "1.11",
        "alt_name" => "Schulungsraum (ehem. Sportr.)",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 2013,
        "location_id" => 9,
        "floor" => "1.OG",
        "name" => "1.12",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 2014,
        "location_id" => 9,
        "floor" => "1.OG",
        "name" => "1.13",
        "alt_name" => "Schulungsraum (Treppe grdaus)",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3102,
        "location_id" => 10,
        "floor" => "EG",
        "name" => "0.02",
        "alt_name" => "Schulungsraum Sprachkurs 1",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3103,
        "location_id" => 10,
        "floor" => "EG",
        "name" => "0.03",
        "alt_name" => "Schulungsraum Sprachkurs 2",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3104,
        "location_id" => 10,
        "floor" => "1.OG",
        "name" => "1.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3109,
        "location_id" => 10,
        "floor" => "1.OG",
        "name" => "1.11",
        "alt_name" => "OSI Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3116,
        "location_id" => 10,
        "floor" => "2.OG",
        "name" => "2.01",
        "alt_name" => "E-Com Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3117,
        "location_id" => 10,
        "floor" => "2.OG",
        "name" => "2.02",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3118,
        "location_id" => 10,
        "floor" => "2.OG",
        "name" => "2.03",
        "alt_name" => "FOSI-Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3120,
        "location_id" => 10,
        "floor" => "2.OG",
        "name" => "2.05",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3121,
        "location_id" => 10,
        "floor" => "2.OG",
        "name" => "2.06",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3123,
        "location_id" => 10,
        "floor" => "2.OG",
        "name" => "2.08",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3128,
        "location_id" => 10,
        "floor" => "3.OG",
        "name" => "3.03",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3002,
        "location_id" => 11,
        "floor" => "5",
        "name" => "5.4",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 3201,
        "location_id" => 12,
        "floor" => "EG",
        "name" => "0.01",
        "alt_name" => "Schulungsraum FM3",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4104,
        "location_id" => 13,
        "floor" => "2.OG",
        "name" => "2.06",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4105,
        "location_id" => 13,
        "floor" => "2.OG",
        "name" => "2.07",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4106,
        "location_id" => 13,
        "floor" => "2.OG",
        "name" => "2.08",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4107,
        "location_id" => 13,
        "floor" => "2.OG",
        "name" => "2.09",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4108,
        "location_id" => 13,
        "floor" => "2.OG",
        "name" => "2.10",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4115,
        "location_id" => 13,
        "floor" => "3.OG",
        "name" => "3.05",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4116,
        "location_id" => 13,
        "floor" => "3.OG",
        "name" => "3.06",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4118,
        "location_id" => 13,
        "floor" => "3.OG",
        "name" => "3.08",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4120,
        "location_id" => 13,
        "floor" => "3.OG",
        "name" => "3.10",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4122,
        "location_id" => 13,
        "floor" => "3.OG",
        "name" => "3.15",
        "alt_name" => "SU",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4125,
        "location_id" => 13,
        "floor" => "4.OG",
        "name" => "4.07",
        "alt_name" => "BUS-Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4126,
        "location_id" => 13,
        "floor" => "4.OG",
        "name" => "4.08",
        "alt_name" => "APO-Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4127,
        "location_id" => 13,
        "floor" => "4.OG",
        "name" => "4.09",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4201,
        "location_id" => 14,
        "floor" => "UG",
        "name" => "1.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4203,
        "location_id" => 14,
        "floor" => "UG",
        "name" => "1.03",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4205,
        "location_id" => 14,
        "floor" => "UG",
        "name" => "1.11",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4001,
        "location_id" => 15,
        "floor" => "2.OG",
        "name" => "2.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4002,
        "location_id" => 15,
        "floor" => "2.OG",
        "name" => "2.02",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4005,
        "location_id" => 15,
        "floor" => "2.OG",
        "name" => "2.05",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4007,
        "location_id" => 15,
        "floor" => "2.OG",
        "name" => "2.10",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4008,
        "location_id" => 15,
        "floor" => "2.OG",
        "name" => "2.11",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 4301,
        "location_id" => 16,
        "floor" => "EG",
        "name" => "0.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5002,
        "location_id" => 17,
        "floor" => "EG",
        "name" => "0.02",
        "alt_name" => "KBM 7 Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5004,
        "location_id" => 17,
        "floor" => "EG",
        "name" => "0.04",
        "alt_name" => "APO/FOSI Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5006,
        "location_id" => 17,
        "floor" => "EG",
        "name" => "0.12",
        "alt_name" => "KBM 6 Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5008,
        "location_id" => 17,
        "floor" => "EG",
        "name" => "0.14",
        "alt_name" => "KBM 8  Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5009,
        "location_id" => 17,
        "floor" => "5.OG",
        "name" => "5.03",
        "alt_name" => "OSI / IBO Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5014,
        "location_id" => 17,
        "floor" => "5.OG",
        "name" => "5.10",
        "alt_name" => "BPW Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5015,
        "location_id" => 17,
        "floor" => "5.OG",
        "name" => "5.11",
        "alt_name" => "KBM 9 Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5101,
        "location_id" => 18,
        "floor" => "EG",
        "name" => "0.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5103,
        "location_id" => 18,
        "floor" => "1.OG",
        "name" => "1.05",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5104,
        "location_id" => 18,
        "floor" => "1.OG",
        "name" => "1.06",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5105,
        "location_id" => 18,
        "floor" => "2.OG",
        "name" => "2.01",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 5106,
        "location_id" => 18,
        "floor" => "2.OG",
        "name" => "2.05",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 6001,
        "location_id" => 19,
        "floor" => "5.OG",
        "name" => "5.02",
        "alt_name" => "VL Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 6004,
        "location_id" => 19,
        "floor" => "5.OG",
        "name" => "5.05",
        "alt_name" => "KBM 2019S Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 6005,
        "location_id" => 19,
        "floor" => "5.OG",
        "name" => "5.06",
        "alt_name" => "FOSI Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 6008,
        "location_id" => 19,
        "floor" => "5.OG",
        "name" => "5.12",
        "alt_name" => "KBM-B-20W Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 6009,
        "location_id" => 19,
        "floor" => "5.OG",
        "name" => "5.13",
        "alt_name" => "OSI/ISO Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 6011,
        "location_id" => 19,
        "floor" => "5.OG",
        "name" => "5.15",
        "alt_name" => "KBM-B-20S Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 6015,
        "location_id" => 19,
        "floor" => "2.OG",
        "name" => "2.17",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 6016,
        "location_id" => 19,
        "floor" => "2.OG",
        "name" => "2.18",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 7002,
        "location_id" => 20,
        "floor" => "6.OG",
        "name" => "6.02",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 7003,
        "location_id" => 20,
        "floor" => "6.OG",
        "name" => "6.03",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 7005,
        "location_id" => 20,
        "floor" => "6.OG",
        "name" => "6.05",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 7008,
        "location_id" => 20,
        "floor" => "6.OG",
        "name" => "6.08",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 7011,
        "location_id" => 20,
        "floor" => "6.OG",
        "name" => "6.14",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ],
      [
        "id" => 7014,
        "location_id" => 20,
        "floor" => "6.OG",
        "name" => "6.09",
        "alt_name" => "Schulungsraum",
        "created_at" => NULL,
        "updated_at" => NULL,
      ]
    ]);
  }
}
